name: Publish Development Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt
      - name: Build
        run: chmod +x ./gradlew && ./gradlew build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4.6.1
        with:
          name: build-artifacts
          path: build/libs
